name: Keep Streamlit app awake

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:     

jobs:
  wake_streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit
        run: |
          curl -s -o /dev/null -A "Mozilla/5.0 (X11; Linux x86_64)" https://hashtaggenerator.streamlit.app/
